apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  ports:
    - port: 80
  selector:
    app: redmine
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-pv-claim
  labels:
    app: redmine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  selector:
    matchLabels:
      app: redmine
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
        tier: frontend
    spec:
      containers:
      - image: redmine:4.2.1-alpine
        name: redmine
        env:
        - name: REDMINE_DB_HOST
          value: redmine-mysql
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: redmine
        volumeMounts:
        - name: redmine-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: redmine-persistent-storage
        persistentVolumeClaim:
          claimName: redmine-pv-claim
